version: '3'
services:
  node:
    image: node:18.16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm start
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
